let languages = [
    ["en" , "English (default) (en)"],
    ["ar" , "Arabic (ar)"],
    ["bg" , "Bulgarian (bg)"],
    ["ca" , "Catalan (ca)"],
    ["hr" , "Croatian (hr)"],
    ["zh-hans" , "Chinese (Simplified) (zh-hans)"],
    ["zh-hant" , "Chinese (Traditional) (zh-hant)"],
    ["cs" , "Czech (cs)"],
    ["da" , "Danish (da)"],
    ["nl" , "Dutch (nl)"],
    ["fi" , "Filipino (fi)"],
    ["fi" , "Finnish (fi)"],
    ["fr" , "French (fr)"],
    ["de" , "German (de)"],
    ["el" , "Greek (el)"],
    ["he" , "Hebrew (he)"],
    ["hi" , "Hindi (hi)"],
    ["hu" , "Hungarian (hu)"],
    ["id" , "Indonesian (id)"],
    ["it" , "Italian (it)"],
    ["ja" , "Japanese (ja)"],
    ["ko" , "Korean (ko)"],
    ["lv" , "Latvian (lv)"],
    ["lt" , "Lithuanian (lt)"],
    ["no" , "Norwegian (no)"],
    ["pl" , "Polish (pl)"],
    ["pt" , "Portuguese (pt)"],
    ["ro" , "Romanian (ro)"],
    ["ru" , "Russian (ru)"],
    ["sr" , "Serbian (sr)"],
    ["sk" , "Slovak (sk)"],
    ["sl" , "Slovenian (sl)"],
    ["es" , "Spanish (es)"],
    ["sv" , "Swedish (sv)"],
    ["th" , "Thai (th)"],
    ["tr" , "Turkish (tr)"],
    ["uk" , "Ukrainian (uk)"],
    ["vi" , "Vietnamese (vi)"]
];
export default languages;