let regions= [ ["us", "United States (us)"],
                          ["af", "Afghanistan (af)"],
                          ["ax", "Åland Islands (ax)"],
                          ["al", "Albania (al)"],
                          ["dz", "Algeria (dz)"],
                          ["as", "American Samoa (as)"],
                          ["ad", "Andorra (ad)"],
                          ["ao", "Angola (ao)"],
                          ["ai", "Anguilla (ai)"],
                          ["aq", "Antarctica (aq)"],
                          ["ag", "Antigua and Barbuda (ag)"],
                          ["ar", "Argentina (ar)"],
                          ["am", "Armenia (am)"],
                          ["aw", "Aruba (aw)"],
                          ["au", "Australia (au)"],
                          ["at", "Austria (at)"],
                          ["az", "Azerbaijan (az)"],
                          ["bs", "Bahamas (bs)"],
                          ["bh", "Bahrain (bh)"],
                          ["bd", "Bangladesh (bd)"],
                          ["bb", "Barbados (bb)"],
                          ["by", "Belarus (by)"],
                          ["be", "Belgium (be)"],
                          ["bz", "Belize (bz)"],
                          ["bj", "Benin (bj)"],
                          ["bm", "Bermuda (bm)"],
                          ["bt", "Bhutan (bt)"],
                          ["bo", "Bolivia, Plurinational State of (bo)"],
                          ["bq", "Bonaire, Sint Eustatius and Saba (bq)"],
                          ["ba", "Bosnia and Herzegovina (ba)"],
                          ["bw", "Botswana (bw)"],
                          ["bv", "Bouvet Island (bv)"],
                          ["br", "Brazil (br)"],
                          ["io", "British Indian Ocean Territory (io)"],
                          ["bn", "Brunei Darussalam (bn)"],
                          ["bg", "Bulgaria (bg)"],
                          ["bf", "Burkina Faso (bf)"],
                          ["bi", "Burundi (bi)"],
                          ["kh", "Cambodia (kh)"],
                          ["cm", "Cameroon (cm)"],
                          ["ca", "Canada (ca)"],
                          ["cv", "Cape Verde (cv)"],
                          ["ky", "Cayman Islands (ky)"],
                          ["cf", "Central African Republic (cf)"],
                          ["td", "Chad (td)"],
                          ["cl", "Chile (cl)"],
                          ["cn", "China (cn)"],
                          ["cx", "Christmas Island (cx)"],
                          ["cc", "Cocos (Keeling) Islands (cc)"],
                          ["co", "Colombia (co)"],
                          ["km", "Comoros (km)"],
                          ["cg", "Congo (cg)"],
                          ["cd", "Congo, the Democratic Republic of the (cd)"],
                          ["ck", "Cook Islands (ck)"],
                          ["cr", "Costa Rica (cr)"],
                          ["ci", "Côte d'Ivoire (ci)"],
                          ["hr", "Croatia (hr)"],
                          ["cu", "Cuba (cu)"],
                          ["cw", "Curaçao (cw)"],
                          ["cy", "Cyprus (cy)"],
                          ["cz", "Czech Republic (cz)"],
                          ["dk", "Denmark (dk)"],
                          ["dj", "Djibouti (dj)"],
                          ["dm", "Dominica (dm)"],
                          ["do", "Dominican Republic (do)"],
                          ["ec", "Ecuador (ec)"],
                          ["eg", "Egypt (eg)"],
                          ["sv", "El Salvador (sv)"],
                          ["gq", "Equatorial Guinea (gq)"],
                          ["er", "Eritrea (er)"],
                          ["ee", "Estonia (ee)"],
                          ["et", "Ethiopia (et)"],
                          ["fk", "Falkland Islands (Malvinas) (fk)"],
                          ["fo", "Faroe Islands (fo)"],
                          ["fj", "Fiji (fj)"],
                          ["fi", "Finland (fi)"],
                          ["fr", "France (fr)"],
                          ["gf", "French Guiana (gf)"],
                          ["pf", "French Polynesia (pf)"],
                          ["tf", "French Southern Territories (tf)"],
                          ["ga", "Gabon (ga)"],
                          ["gm", "Gambia (gm)"],
                          ["ge", "Georgia (ge)"],
                          ["de", "Germany (de)"],
                          ["gh", "Ghana (gh)"],
                          ["gi", "Gibraltar (gi)"],
                          ["gr", "Greece (gr)"],
                          ["gl", "Greenland (gl)"],
                          ["gd", "Grenada (gd)"],
                          ["gp", "Guadeloupe (gp)"],
                          ["gu", "Guam (gu)"],
                          ["gt", "Guatemala (gt)"],
                          ["gg", "Guernsey (gg)"],
                          ["gn", "Guinea (gn)"],
                          ["gw", "Guinea-Bissau (gw)"],
                          ["gy", "Guyana (gy)"],
                          ["ht", "Haiti (ht)"],
                          ["hm", "Heard Island and McDonald Islands (hm)"],
                          ["va", "Holy See (Vatican City State) (va)"],
                          ["hn", "Honduras (hn)"],
                          ["hk", "Hong Kong (hk)"],
                          ["hu", "Hungary (hu)"],
                          ["is", "Iceland (is)"],
                          ["in", "India (in)"],
                          ["id", "Indonesia (id)"],
                          ["ir", "Iran, Islamic Republic of (ir)"],
                          ["iq", "Iraq (iq)"],
                          ["ie", "Ireland (ie)"],
                          ["im", "Isle of Man (im)"],
                          ["il", "Israel (il)"],
                          ["it", "Italy (it)"],
                          ["jm", "Jamaica (jm)"],
                          ["jp", "Japan (jp)"],
                          ["je", "Jersey (je)"],
                          ["jo", "Jordan (jo)"],
                          ["kz", "Kazakhstan (kz)"],
                          ["ke", "Kenya (ke)"],
                          ["ki", "Kiribati (ki)"],
                          ["kp", "Korea, Democratic People's Republic of (kp)"],
                          ["kr", "Korea, Republic of (kr)"],
                          ["kw", "Kuwait (kw)"],
                          ["kg", "Kyrgyzstan (kg)"],
                          ["la", "Lao People's Democratic Republic (la)"],
                          ["lv", "Latvia (lv)"],
                          ["lb", "Lebanon (lb)"],
                          ["ls", "Lesotho (ls)"],
                          ["lr", "Liberia (lr)"],
                          ["ly", "Libya (ly)"],
                          ["li", "Liechtenstein (li)"],
                          ["lt", "Lithuania (lt)"],
                          ["lu", "Luxembourg (lu)"],
                          ["mo", "Macao (mo)"],
                          ["mk", "Macedonia, the former Yugoslav Republic of (mk)"],
                          ["mg", "Madagascar (mg)"],
                          ["mw", "Malawi (mw)"],
                          ["my", "Malaysia (my)"],
                          ["mv", "Maldives (mv)"],
                          ["ml", "Mali (ml)"],
                          ["mt", "Malta (mt)"],
                          ["mh", "Marshall Islands (mh)"],
                          ["mq", "Martinique (mq)"],
                          ["mr", "Mauritania (mr)"],
                          ["mu", "Mauritius (mu)"],
                          ["yt", "Mayotte (yt)"],
                          ["mx", "Mexico (mx)"],
                          ["fm", "Micronesia, Federated States of (fm)"],
                          ["md", "Moldova, Republic of (md)"],
                          ["mc", "Monaco (mc)"],
                          ["mn", "Mongolia (mn)"],
                          ["me", "Montenegro (me)"],
                          ["ms", "Montserrat (ms)"],
                          ["ma", "Morocco (ma)"],
                          ["mz", "Mozambique (mz)"],
                          ["mm", "Myanmar (mm)"],
                          ["na", "Namibia (na)"],
                          ["nr", "Nauru (nr)"],
                          ["np", "Nepal (np)"],
                          ["nl", "Netherlands (nl)"],
                          ["nc", "New Caledonia (nc)"],
                          ["nz", "New Zealand (nz)"],
                          ["ni", "Nicaragua (ni)"],
                          ["ne", "Niger (ne)"],
                          ["ng", "Nigeria (ng)"],
                          ["nu", "Niue (nu)"],
                          ["nf", "Norfolk Island (nf)"],
                          ["mp", "Northern Mariana Islands (mp)"],
                          ["no", "Norway (no)"],
                          ["om", "Oman (om)"],
                          ["pk", "Pakistan (pk)"],
                          ["pw", "Palau (pw)"],
                          ["ps", "Palestinian Territory, Occupied (ps)"],
                          ["pa", "Panama (pa)"],
                          ["pg", "Papua New Guinea (pg)"],
                          ["py", "Paraguay (py)"],
                          ["pe", "Peru (pe)"],
                          ["ph", "Philippines (ph)"],
                          ["pn", "Pitcairn (pn)"],
                          ["pl", "Poland (pl)"],
                          ["pt", "Portugal (pt)"],
                          ["pr", "Puerto Rico (pr)"],
                          ["qa", "Qatar (qa)"],
                          ["re", "Réunion (re)"],
                          ["ro", "Romania (ro)"],
                          ["ru", "Russian Federation (ru)"],
                          ["rw", "Rwanda (rw)"],
                          ["bl", "Saint Barthélemy (bl)"],
                          ["sh", "Saint Helena, Ascension and Tristan da Cunha (sh)"],
                          ["kn", "Saint Kitts and Nevis (kn)"],
                          ["lc", "Saint Lucia (lc)"],
                          ["mf", "Saint Martin (French part) (mf)"],
                          ["pm", "Saint Pierre and Miquelon (pm)"],
                          ["vc", "Saint Vincent and the Grenadines (vc)"],
                          ["ws", "Samoa (ws)"],
                          ["sm", "San Marino (sm)"],
                          ["st", "Sao Tome and Principe (st)"],
                          ["sa", "Saudi Arabia (sa)"],
                          ["sn", "Senegal (sn)"],
                          ["rs", "Serbia (rs)"],
                          ["sc", "Seychelles (sc)"],
                          ["sl", "Sierra Leone (sl)"],
                          ["sg", "Singapore (sg)"],
                          ["sx", "Sint Maarten (Dutch part) (sx)"],
                          ["sk", "Slovakia (sk)"],
                          ["si", "Slovenia (si)"],
                          ["sb", "Solomon Islands (sb)"],
                          ["so", "Somalia (so)"],
                          ["za", "South Africa (za)"],
                          ["gs", "South Georgia and the South Sandwich Islands (gs)"],
                          ["ss", "South Sudan (ss)"],
                          ["es", "Spain (es)"],
                          ["lk", "Sri Lanka (lk)"],
                          ["sd", "Sudan (sd)"],
                          ["sr", "Suriname (sr)"],
                          ["sj", "Svalbard and Jan Mayen (sj)"],
                          ["sz", "Swaziland (sz)"],
                          ["se", "Sweden (se)"],
                          ["ch", "Switzerland (ch)"],
                          ["sy", "Syrian Arab Republic (sy)"],
                          ["tw", "Taiwan, Province of China (tw)"],
                          ["tj", "Tajikistan (tj)"],
                          ["tz", "Tanzania, United Republic of (tz)"],
                          ["th", "Thailand (th)"],
                          ["tl", "Timor-Leste (tl)"],
                          ["tg", "Togo (tg)"],
                          ["tk", "Tokelau (tk)"],
                          ["to", "Tonga (to)"],
                          ["tt", "Trinidad and Tobago (tt)"],
                          ["tn", "Tunisia (tn)"],
                          ["tr", "Turkey (tr)"],
                          ["tm", "Turkmenistan (tm)"],
                          ["tc", "Turks and Caicos Islands (tc)"],
                          ["tv", "Tuvalu (tv)"],
                          ["ug", "Uganda (ug)"],
                          ["ua", "Ukraine (ua)"],
                          ["ae", "United Arab Emirates (ae)"],
                          ["gb", "United Kingdom (gb)"],
                          ["um", "United States Minor Outlying Islands (um)"],
                          ["uy", "Uruguay (uy)"],
                          ["uz", "Uzbekistan (uz)"],
                          ["vu", "Vanuatu (vu)"],
                          ["ve", "Venezuela, Bolivarian Republic of (ve)"],
                          ["vn", "Viet Nam (vn)"],
                          ["vg", "Virgin Islands, British (vg)"],
                          ["vi", "Virgin Islands, U.S. (vi)"],
                          ["wf", "Wallis and Futuna (wf)"],
                          ["eh", "Western Sahara (eh)"],
                          ["ye", "Yemen (ye)"],
                          ["zm", "Zambia (zm)"],
                          ["zw", "Zimbabwe (zw)"]];

export default regions;